import { Module } from '@nestjs/common';
import {
  AddressesUseCaseModule,
  CartUseCasesModule,
  CategoriesUseCasesModule,
  CommentsUseCasesModule,
  ImagesUseCasesModule,
  PaymentsUseCasesModule,
  ProductsUseCasesModule,
  PromotionsUseCasesModule,
  ReviewsUseCasesModule,
  SeasonsUseCasesModule,
  SharedUseCasesModule,
  TagsUseCasesModule,
  UserUseCasesModule,
  VariationsUseCasesModule,
} from './';

@Module({
  imports: [
    AddressesUseCaseModule,
    CartUseCasesModule,
    CategoriesUseCasesModule,
    CommentsUseCasesModule,
    ImagesUseCasesModule,
    PaymentsUseCasesModule,
    ProductsUseCasesModule,
    PromotionsUseCasesModule,
    ReviewsUseCasesModule,
    SharedUseCasesModule,
    SeasonsUseCasesModule,
    TagsUseCasesModule,
    UserUseCasesModule,
    VariationsUseCasesModule,
  ],
  exports: [
    AddressesUseCaseModule,
    CartUseCasesModule,
    CategoriesUseCasesModule,
    CommentsUseCasesModule,
    ImagesUseCasesModule,
    PaymentsUseCasesModule,
    ProductsUseCasesModule,
    PromotionsUseCasesModule,
    ReviewsUseCasesModule,
    SharedUseCasesModule,
    SeasonsUseCasesModule,
    TagsUseCasesModule,
    UserUseCasesModule,
    VariationsUseCasesModule,
  ],
})
export class UseCasesModule {}
